# Generated by Django 6.0.3 on 2026-03-29 15:49

import django.db.models.deletion
from django.db import migrations, models


def copy_taxonomy_fields_to_translations(apps, schema_editor):
    Series = apps.get_model("legends", "Series")
    SeriesTranslation = apps.get_model("legends", "SeriesTranslation")
    Province = apps.get_model("legends", "Province")
    ProvinceTranslation = apps.get_model("legends", "ProvinceTranslation")
    Patron = apps.get_model("legends", "Patron")
    PatronTranslation = apps.get_model("legends", "PatronTranslation")
    Tag = apps.get_model("legends", "Tag")
    TagTranslation = apps.get_model("legends", "TagTranslation")

    for item in Series.objects.all():
        SeriesTranslation.objects.get_or_create(
            series=item,
            locale="ru",
            defaults={
                "name": item.name,
                "slug": item.slug,
                "description": item.description,
                "is_published": True,
            },
        )

    for item in Province.objects.all():
        ProvinceTranslation.objects.get_or_create(
            province=item,
            locale="ru",
            defaults={
                "name": item.name,
                "slug": item.slug,
                "description": item.description,
                "is_published": True,
            },
        )

    for item in Patron.objects.all():
        PatronTranslation.objects.get_or_create(
            patron=item,
            locale="ru",
            defaults={
                "name": item.name,
                "slug": item.slug,
                "description": item.description,
                "is_published": True,
            },
        )

    for item in Tag.objects.all():
        TagTranslation.objects.get_or_create(
            tag=item,
            locale="ru",
            defaults={
                "name": item.name,
                "slug": item.slug,
                "description": item.description,
                "is_published": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("legends", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patron",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="PatronTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("ru", "Russian"), ("en", "English"), ("de", "German"), ("es", "Spanish")], max_length=2)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("patron", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="legends.patron")),
            ],
            options={
                "ordering": ("locale", "name"),
                "indexes": [
                    models.Index(fields=["locale", "slug"], name="legends_pat_locale_4dec07_idx"),
                    models.Index(fields=["is_published", "locale"], name="legends_pat_is_publ_1a811c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("patron", "locale"), name="unique_patron_translation_per_locale"),
                    models.UniqueConstraint(fields=("locale", "slug"), name="unique_patron_translation_slug_per_locale"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProvinceTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("ru", "Russian"), ("en", "English"), ("de", "German"), ("es", "Spanish")], max_length=2)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("province", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="legends.province")),
            ],
            options={
                "ordering": ("locale", "name"),
                "indexes": [
                    models.Index(fields=["locale", "slug"], name="legends_pro_locale_f4eb48_idx"),
                    models.Index(fields=["is_published", "locale"], name="legends_pro_is_publ_17dccb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("province", "locale"), name="unique_province_translation_per_locale"),
                    models.UniqueConstraint(fields=("locale", "slug"), name="unique_province_translation_slug_per_locale"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SeriesTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("ru", "Russian"), ("en", "English"), ("de", "German"), ("es", "Spanish")], max_length=2)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("series", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="legends.series")),
            ],
            options={
                "ordering": ("locale", "name"),
                "indexes": [
                    models.Index(fields=["locale", "slug"], name="legends_ser_locale_25ba70_idx"),
                    models.Index(fields=["is_published", "locale"], name="legends_ser_is_publ_b8f1a7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("series", "locale"), name="unique_series_translation_per_locale"),
                    models.UniqueConstraint(fields=("locale", "slug"), name="unique_series_translation_slug_per_locale"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TagTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locale", models.CharField(choices=[("ru", "Russian"), ("en", "English"), ("de", "German"), ("es", "Spanish")], max_length=2)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("tag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="legends.tag")),
            ],
            options={
                "ordering": ("locale", "name"),
                "indexes": [
                    models.Index(fields=["locale", "slug"], name="legends_tag_locale_c7d9b3_idx"),
                    models.Index(fields=["is_published", "locale"], name="legends_tag_is_publ_4de757_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tag", "locale"), name="unique_tag_translation_per_locale"),
                    models.UniqueConstraint(fields=("locale", "slug"), name="unique_tag_translation_slug_per_locale"),
                ],
            },
        ),
        migrations.RunPython(copy_taxonomy_fields_to_translations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="patron",
            name="description",
        ),
        migrations.RemoveField(
            model_name="patron",
            name="name",
        ),
        migrations.RemoveField(
            model_name="patron",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="province",
            name="description",
        ),
        migrations.RemoveField(
            model_name="province",
            name="name",
        ),
        migrations.RemoveField(
            model_name="province",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="series",
            name="description",
        ),
        migrations.RemoveField(
            model_name="series",
            name="name",
        ),
        migrations.RemoveField(
            model_name="series",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
    ]
